### PR TITLE
added final text to markdown files

### PR DESCRIPTION
**Pull request by mehan**
I added all of the NSF-approved final text to the markdown files

### CODE REVIEW

**Comment by ScottDowne** [comment]
Amazing! How did you feel about the process of doing changes like this in MD?

Just give me a few minutes to take a look at this and land it.

**Comment by ScottDowne** [comment]
This looks good to me. Landing.

**Comment by ScottDowne** [comment]
I'll fix this merge conflict, it's my fault.

**Comment by ScottDowne** [comment]
Thanks! Let me know if I borked something in the rebase, as it's the first time I've used github to fix a merge conflict. I usually do it via git. It was new to me.

**Comment by mehan** [comment]
Thanks for this, @ScottDowne! Based on a quick scan, the rebase doesn't seem to have effected any of the changes in my PR.

As for editing this stuff in the Markdown files, I thought it was very easy and straightforward and I really like having the ability to be able to make these tweaks myself. npm made things super painless in terms of installing dependencies, building the site and running it locally. And I'm always happy to have an excuse to use GitHub in my day to day work. 😄

**Pull request merged**
