### PR TITLE
Adding GA script

### PR DESCRIPTION
**Pull request by ScottDowne**

### CODE REVIEW

**Comment by alanmoo** [comment]
Travis isn't happy

**Comment by alanmoo** [comment]
Assigned this to multiple of us for whoever can review it first

**Comment by ScottDowne** [comment]
Pushed up a change that should fix travis.

**Review by alanmoo — CHANGES_REQUESTED** [review]
Update the CSP settings in `header.pug` to allow GA

**Comment by ScottDowne** [comment]
Updated, should be good now.

**Review by alanmoo — APPROVED** [review]

**Pull request merged**
