### PR TITLE
updating deps

### PR DESCRIPTION
**Pull request by gvn**

### CODE REVIEW

**Comment by alanmoo** [comment]
Is this on heroku? I wanted to spin up a review app but I don't see it.

**Comment by gvn** [comment]
I don't think so. I'm actually not sure how this is deployed... CC: @ScottDowne

**Comment by alanmoo** [comment]
@ScottDowne ^ ?

**Comment by gvn** [comment]
Since this is a static generated site I'm assuming Jenkins.

**Comment by ScottDowne** [comment]
It's on jenkins

**Review by alanmoo — APPROVED** [review]
This works, but

**Comment by gvn** [comment]
> This works, but

Was there more to that sentence? 🤔

**Comment by alanmoo** [comment]
Oh weird. GitHub bug while I was re-testing something. Works fine.

**Pull request merged**
