### PR TITLE
Remove info about teams expander.

### PR DESCRIPTION
**Pull request by ScottDowne**

### CODE REVIEW

**Comment by ScottDowne** [comment]
I'm seeing a flaw in index based files for this. Should probably make the file names content based.

**Comment by ScottDowne** [comment]
Fixing https://github.com/mozilla/nsf-challenge/issues/42

**Comment by ScottDowne** [comment]
@mehan If you want, feel free to review this one.

**Comment by mehan** [comment]
@ScottDowne This one looks good too, thanks!

**Pull request merged**
