### PR TITLE
Adding judges to nsf site.

### PR DESCRIPTION
**Pull request by ScottDowne**

### CODE REVIEW

**Comment by ScottDowne** [comment]
@mehan OK, structure is done in this pull request.

It's missing three judge headshots, and I didn't do the links in the judge bios yet.

The links in the bios should be easy and done in markdown.

Thoughts?

**Comment by mehan** [comment]
@ScottDowne This is looking good! A few minor suggestions:

screen shot 2018-02-09 at 2 53 47 pm

- Change the "Winners" text in the above black banner to read "Design Concept (Stage 1) Award Winners"

screen shot 2018-02-09 at 2 49 42 pm

- Could the above tabs read "Challenge 1" and "Challenge 2"?

screen shot 2018-02-09 at 2 46 02 pm

- In the above text, the all-caps title seems a bit inconsistent with the styling on the rest of the page--suggest formatting this as titlecase instead.

- Also in the above, could you append the following text to the end of the italic paragraphs for both Challenge 1 and 2: "The following awards recognize outstanding achievement during the Design Concept Stage (Stage 1) of the Challenge:"

- The judges section looks good, though now that I'm seeing it on the page, I'm wondering if we could collapse it somehow--maybe hide it behind some sort of accordion?

Thanks!

**Comment by ScottDowne** [comment]
@mehan Updates. I didn't add  any accordions yet. We can discus that Monday.

I also wasn't sure how you wanted the line of text under the italics in the winners sections, so I made it another paragraph. I also wondered if you wanted it as more italic, we can do either easily, as that bit is in markdown.

**Comment by mehan** [comment]
@ScottDowne This all looks great! I think the accordion is the last thing remaining--happy to talk through that whenever you're free.

**Comment by mehan** [comment]
I think this looks great! Just one minor fix--the formatting for judges' Twitter links is inconsistent, as seen in the screenshot below:

screen shot 2018-02-16 at 11 38 47 am

The following judges entries need to be normalized: 

- Heather Williams
- Christopher Mitchell
- Amalia Deloney
- Ryan Gerety
- Steve Song
- Catherine Middleton
- Alex Gil

**Comment by mehan** [comment]
Looks good now. 👍 Thanks!

**Pull request merged**
